### ISSUE TITLE
<time.h> not included in amalgamated headers/source

### ISSUE THREAD

**Issue by emma-campbell** [vberlier/unicorn#11]
Attempting to compile my tests and running into this error...

<img width="810" alt="Screen Shot 2020-03-31 at 1 03 29 PM" src="https://user-images.githubusercontent.com/44985049/78401633-2c46ca80-75c7-11ea-96f4-0c169d0ed7db.png">

I can fix within my system including <time.h> in the header and source within /dist but thats just a workaround and not an actual solution.

**Comment by vberlier** [comment]
Thanks for reporting this! Fixed in 0.4.11.
