### ISSUE TITLE
String mismatch marker

### ISSUE THREAD

**Issue by eerimoq** [vberlier/unicorn#5]
Hello!

Adding a marker at the first character mismatch when comparing string would make it easier to identify where the string differs.

Current error:

```
Location: main.c:5
Time:     0.07ms
Error:    Assertion "1234567890" == "1234567790" failed.
          First argument "1234567890" is not equal to "1234567790".
```

Requested error:

```
Location: main.c:5
Time:     0.07ms
Error:    Assertion "1234567890" == "1234567790" failed.
          First argument "1234567890" is not equal to "1234567790".
                                 ^                            ^
```

Sample program:
    
``` c
#include <unicorn/unicorn.h>

TEST(test_1)
{
    ASSERT_EQ("1234567890", "1234567790");
}

int main()
{
    return RUN_TESTS(
        test_1
    );
}
```

**Comment by vberlier** [comment]
Agreed, for strings the current way of reporting the failed assertion is really not helpful. I'll try to show a clean diff that highlights the added and removed substrings.

**Comment by vberlier** [comment]
Okay so I started working on this, long strings with new lines are now taken into account when formatting the error message.

```sh
Location: test/run_tests.c:11
Time:     0.50ms
Error:    Assertion "multiline\nstring" == "gets formatted\nproperly" failed.
          First argument "
              multiline
              string
          " is not equal to "
              gets formatted
              properly
          ".
```

It works with any kind of binary assertion (like `ASSERT_SUBSTRING` but also `ASSERT_NE`, `ASSERT_LT`, etc...). Now I still want to show a diff for `ASSERT_EQ` specifically.

**Comment by vberlier** [comment]
Just implemented a line-by-line diff for `ASSERT_EQ`!

It currently looks like this (with a string from one of your tests):

![image](https://user-images.githubusercontent.com/24430071/59435335-a5352580-8ded-11e9-9b7c-b43eb7793f08.png)

I also have everything I need to show an inline diff as well but I haven't decided how the characters should be highlighted yet.

**Comment by vberlier** [comment]
Alright so the diff now only highlights the characters that have changed instead of the whole line:

![image](https://user-images.githubusercontent.com/24430071/59643752-457ea780-916a-11e9-85ee-f7ab77ef28b2.png)

The output of your original sample program now looks like this:

![image](https://user-images.githubusercontent.com/24430071/59643886-d05fa200-916a-11e9-9389-63417bc4e5ae.png)

I'm closing the issue but feel free to reopen it if you think I missed something.
